FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    curl \
    vim \
    git \
    python3 \
    python3-pip

WORKDIR /app

COPY . .

RUN pip3 install -r requirements.txt

CMD ["python3", "datamodelling.py"]