apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: data-preprocessing-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-preprocessing-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80e
