apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: data-preprocessing
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      containers:
      - name: data-preprocessing
        image: loocoos/dataprocessing:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 128Mi
            cpu: 0.1
        volumeMounts:
        - mountPath: /data
          name: vol-storage
      volumes:
      - name: vol-storage
        persistentVolumeClaim:
          claimName: pvc-pod
